spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/offers-ms?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  config:
    import: optional:configserver:http://localhost:5000




server:
  port: 5006

folders :
  cv: "C:\\IOC_CDI\\FreelanceApp\\account-service\\files\\cvs"
  profile: "C:\\IOC_CDI\\FreelanceApp\\account-service\\files\\profile_images"


