services:
  mysql:
    container_name: ms_mysql
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mysql:/data/mysql
    ports:
      - "3306:3306"
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge

volumes:
  mysql: