spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment-ms?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.freelance.payment.dtos.PaymentNotificationRequest
  config:
    import: optional:configserver:http://localhost:5000
server:
  port: 5006