spring:
  application:
    name: skills-microservice
  datasource:
    url: jdbc:mysql://localhost:3306/skills-ms?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  config:
    import: optional:configserver:http://localhost:5000
server:
  port: 5003